### ISSUE TITLE
pycure 装不上, .....

### ISSUE THREAD

**Issue by jp1017** [cls1991/12306-ticket-query#2]
命令行和pycharm都不行?你怎么安装的呢?

py3 不支持? 找不到StringIO,,,

**Comment by cls1991** [comment]
能否提供一下错误信息 @jp1017

**Comment by jp1017** [comment]
```
Collecting pycurl==7.19.5.1
  Downloading pycurl-7.19.5.1.tar.gz (142kB)
    100% |████████████████████████████████| 143kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rt0A6k/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/tmp/pip-build-rt0A6k/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/tmp/pip-build-rt0A6k/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/tmp/pip-build-rt0A6k/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rt0A6k/pycurl/
```

**Comment by cls1991** [comment]
http://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing
根据自己的系统, 安装依赖包. @jp1017

**Comment by jp1017** [comment]
@cls1991 Successfully installed pycurl-7.19.5.1  :+1: 

感谢, 忘记了 google, :cry:

**Comment by jp1017** [comment]
@cls1991 打印格式感觉还有待优化哦,,, :smile:

**Comment by cls1991** [comment]
颜色标注? 还是其他的思路? @jp1017 
另外,  准备引入邮件订阅功能(即简单的余票提醒).

**Comment by jp1017** [comment]
竖向没有对齐...订阅功能不错赛

**Comment by cls1991** [comment]
还有你觉得啥不好的地方, 欢迎提pr @jp1017

**Comment by jp1017** [comment]
刚入 python 坑, 一起学习啊,哈哈哈

**Comment by jp1017** [comment]
对了,py3可以考虑支持下

**Comment by cls1991** [comment]
ok, 回头我测试一下

**Comment by cls1991** [comment]
@jp1017  支持python3

**Comment by jp1017** [comment]
@cls1991 刚看到了. 😄 👍
